services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  server:
    build: ./server
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mysql
      - redis
    networks:
      - app-network
    volumes:
      - ./server/uploads:/app/uploads

  client:
    build: ./client
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network
    environment:
      - VITE_API_URL=https://spa-app-websocket-server.up.railway.app/

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLPASSWORD}
      MYSQLDATABASE: ${MYSQLDATABASE}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
